<?php

namespace AppBundle\Repository;

/**
 * AttachmentConsultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachmentConsultationRepository extends \Doctrine\ORM\EntityRepository
{
}
