<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Client;
use AppBundle\Entity\Consultation;

/**
 * ConsultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Find consultation by its client
     *
     * @param Client $Client
     *
     * @return Consultation|null
     */
    public function findConsultationByClientIDs($client)
    {
        $qb = $this->createQueryBuilder('v');

/*        return $qb->join('v.consultation', 'd')
            ->where($qb->expr()->eq('v.client', ':clientID'))
            ->setParameters([
                'clientID' => $client
            ])
            ->getQuery()
            ->getOneOrNullResult();*/


        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Consultation p where p.client = '. $client .'ORDER BY p.created ASC'
            )
            ->getResult();
    }
}
