<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Client;

/**
 * ConsultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Find village by its slug and slug of its district
     *
     * @param Client $Client
     *
     * @return Village|null
     */
    public function findByClientIDs($client)
    {
        $qb = $this->createQueryBuilder('v');

        return $qb->join('v.client', 'd')
            ->where($qb->expr()->eq('v.id', ':clientID'))
            ->setParameters([
                'clientID' => $client
            ])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
