<?php

namespace AppBundle\Repository;

/**
 * PhotosConsultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotosConsultationRepository extends \Doctrine\ORM\EntityRepository
{
}
