<?php

namespace AppBundle\Repository;

/**
 * RemainderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemainderRepository extends \Doctrine\ORM\EntityRepository
{
}
