<?php

namespace AppBundle\Repository;

/**
 * UserSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
