app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#admin:
#    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#    prefix: /adminClient
#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /adminClient